name: selective_gp
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2025.11.4=haa95532_0
  - cudatoolkit=10.2.89=h74a9793_1
  - flit-core=3.6.0=pyhd3eb1b0_0
  - freetype=2.13.3=h0620614_0
  - intel-openmp=2021.4.0=haa95532_3556
  - jpeg=9b=hb83a4c4_2
  - lerc=4.0.0=h5da7b33_0
  - libdeflate=1.17=h2bbff1b_1
  - libpng=1.6.50=h46444df_0
  - libtiff=4.5.0=h8a3f274_0
  - libuv=1.48.0=h827c3e9_0
  - libwebp=1.2.4=h2bbff1b_0
  - libwebp-base=1.2.4=h2bbff1b_1
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py37h2bbff1b_0
  - mkl_fft=1.3.1=py37h277e83a_0
  - mkl_random=1.2.2=py37hf11a4ad_0
  - ninja=1.12.1=haa95532_0
  - ninja-base=1.12.1=h4157e71_0
  - olefile=0.46=pyhd3eb1b0_0
  - openssl=3.0.18=h543e019_0
  - python=3.7.1=h33f27b4_4
  - pytorch=1.7.1=py3.7_cuda102_cudnn7_0
  - setuptools=65.6.3=py37haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - torchvision=0.8.2=py37_cu102
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.38.4=py37haa95532_0
  - wincertstore=0.2=py37haa95532_2
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - absl-py==0.10.0
      - aiohttp==3.6.2
      - alabaster==0.7.12
      - alembic==1.4.2
      - appnope==0.1.0
      - async-timeout==3.0.1
      - attrs==19.3.0
      - babel==2.8.0
      - backcall==0.1.0
      - bleach==3.1.4
      - cachetools==4.1.1
      - certifi==2020.4.5.1
      - cffi==1.14.0
      - chardet==3.0.4
      - click==7.1.2
      - cloudpickle==1.4.1
      - colorama==0.4.6
      - cycler==0.10.0
      - databricks-cli==0.11.0
      - decorator==4.4.2
      - defusedxml==0.6.0
      - docker==4.2.1
      - docutils==0.16
      - entrypoints==0.3
      - flask==1.1.2
      - future==0.18.2
      - gitdb==4.0.5
      - gitpython==3.1.3
      - google-auth==1.22.0
      - google-auth-oauthlib==0.4.1
      - gorilla==0.3.0
      - gpytorch==1.1.1
      - grpcio==1.32.0
      - gunicorn==20.0.4
      - idna==2.9
      - imagesize==1.2.0
      - importlib-metadata==1.6.0
      - ipdb==0.13.2
      - ipykernel==5.1.4
      - ipython==7.15.0
      - ipython-genutils==0.2.0
      - ipywidgets==7.5.1
      - itsdangerous==1.1.0
      - jedi==0.17.0
      - jinja2==2.11.2
      - joblib==0.15.1
      - jsonschema==3.2.0
      - jupyter==1.0.0
      - jupyter-client==6.1.3
      - jupyter-console==6.1.0
      - jupyter-core==4.6.3
      - kiwisolver==1.2.0
      - latexcodec==2.0.1
      - mako==1.1.3
      - markdown==3.2.2
      - markupsafe==1.1.1
      - matplotlib==3.2.1
      - mistune==0.8.4
      - mlflow==1.8.0
      - multidict==4.7.6
      - nbconvert==5.6.1
      - nbformat==5.0.6
      - networkx==2.5
      - notebook==6.0.3
      - numpy==1.19.2
      - oauthlib==3.1.0
      - oset==0.1.3
      - packaging==20.4
      - pandas==1.0.4
      - pandocfilters==1.4.2
      - parso==0.7.0
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pip==24.0
      - pip-autoremove==0.9.1
      - pipdeptree==0.13.2
      - prometheus-client==0.8.0
      - prometheus-flask-exporter==0.13.0
      - prompt-toolkit==3.0.5
      - protobuf==3.12.2
      - ptyprocess==0.6.0
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pybtex==0.22.2
      - pybtex-docutils==0.2.2
      - pycparser==2.20
      - pygments==2.6.1
      - pyparsing==2.4.7
      - pypiwin32==223
      - pyrsistent==0.16.0
      - python-dateutil==2.8.1
      - python-editor==1.0.4
      - pytz==2020.1
      - pywin32==308
      - pywinpty==2.0.10
      - pyyaml==5.3.1
      - pyzmq==18.1.1
      - qtconsole==4.7.4
      - qtpy==1.9.0
      - querystring-parser==1.2.4
      - requests==2.23.0
      - requests-oauthlib==1.3.0
      - retrying==1.3.3
      - rsa==4.6
      - scikit-learn==0.23.1
      - scipy==1.4.1
      - seaborn==0.11.0
      - send2trash==1.5.0
      - simplejson==3.17.0
      - six==1.15.0
      - smmap==3.0.4
      - snowballstemmer==2.0.0
      - sphinx==3.2.1
      - sphinx-rtd-theme==0.5.0
      - sphinxcontrib-applehelp==1.0.2
      - sphinxcontrib-bibtex==1.0.0
      - sphinxcontrib-devhelp==1.0.2
      - sphinxcontrib-htmlhelp==1.0.3
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.3
      - sphinxcontrib-serializinghtml==1.1.4
      - sqlalchemy==1.3.13
      - sqlparse==0.3.1
      - tabulate==0.8.7
      - tensorboard==2.2.2
      - tensorboard-plugin-wit==1.7.0
      - terminado==0.8.3
      - testpath==0.4.4
      - threadpoolctl==2.1.0
      - tornado==6.0.4
      - tqdm==4.46.1
      - traitlets==4.3.3
      - typing-extensions==3.7.4.3
      - urllib3==1.25.9
      - waitress==2.1.2
      - wcwidth==0.2.3
      - webencodings==0.5.1
      - websocket-client==0.57.0
      - werkzeug==1.0.1
      - widgetsnbextension==3.5.1
      - xlrd==1.2.0
      - yarl==1.6.0
      - zipp==3.1.0
prefix: C:\Users\imb2a\anaconda3\envs\selective_gp
